services:
  - type: web
    name: zargos-discord-search
    env: python
    buildCommand: apt-get update && apt-get install -y megatools && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: ZAGROS_PASSWORD
        generateValue: true
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_YI6ZW9fPlFAD@ep-broad-salad-a4ylvifz-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require
